  @startuml
    component [fluentapi] #Green
    component [processing]
    component [domain]
    component [assertions]
    component [extraction]
    component [projections]
    component [uml]
    component [error]
    component [util] #Grey
    [fluentapi] -> [processing]
    [fluentapi] -> [domain]
    [fluentapi] -> [assertions]
    [fluentapi] -> [extraction]
    [fluentapi] -> [projections]
    [fluentapi] -> [uml]
    [processing] --> [domain]
    [assertions] --> [processing]
    [extraction] --> [domain]
    [extraction] --> [error]
    [extraction] --> [util]
    [projections] --> [domain]
    [projections] --> [processing]
    [projections] --> [util]
    [uml] --> [processing]
    [uml] --> [assertions]
@enduml
