export * from "./src/files-legacy/Project"
export * from "./src/files-legacy/Result"
export * from "./src/files-legacy/Rule"
export * from "./src/files-legacy/TSArch"
export * from "./src/jest/ArchMatchers"
export * from "./src/slices/fluentapi/slices"
